spring:
  application:
    name: employee-system-prod
  
  # Production Database
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  
  # JPA for Production
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

# Production JWT
auth:
  jwt:
    secret-key: ${JWT_SECRET}
    token-expiration: 1800000

# Production Logging
logging:
  level:
    root: WARN
    com.example: INFO